CREATE TABLE room
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    PRIMARY KEY (id)
);

create table cinema_row
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY,
    room_id BIGINT,
    number  INTEGER,
    PRIMARY KEY (id),
    FOREIGN KEY (room_id) REFERENCES room
);

CREATE TABLE seat
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY,
    seat_column INTEGER,
    row_id      BIGINT,
    PRIMARY KEY (id),
    FOREIGN KEY (row_id) REFERENCES cinema_row
);

CREATE TABLE movie
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY,
    title VARCHAR(255),
    PRIMARY KEY (id)
);

CREATE TABLE screening
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY,
    movie_id  BIGINT,
    room_id   BIGINT,
    beginning TIMESTAMP(0),
    ending    TIMESTAMP(0),
    PRIMARY KEY (id),
    FOREIGN KEY (movie_id) REFERENCES movie,
    FOREIGN KEY (room_id) REFERENCES room
);

CREATE TABLE money
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY,
    currency VARCHAR(3),
    amount   NUMERIC(19, 4),
    PRIMARY KEY (id)
);

CREATE TABLE reservation
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY,
    status     VARCHAR(32),
    first_name VARCHAR(255),
    last_name  VARCHAR(255),
    created_at TIMESTAMP(0),
    expires_at TIMESTAMP(0),
    PRIMARY KEY (id)
);

CREATE TABLE ticket
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY,
    status         VARCHAR(32),
    price_id       BIGINT,
    screening_id   BIGINT,
    seat_id        BIGINT,
    reservation_id BIGINT,
    PRIMARY KEY (id),
    FOREIGN KEY (price_id) REFERENCES money,
    FOREIGN KEY (screening_id) REFERENCES screening,
    FOREIGN KEY (seat_id) REFERENCES seat,
    FOREIGN KEY (reservation_id) REFERENCES reservation
);

